import '@duannx/vue-router-transition'
import 'better-auth'
import 'superjson'
import '@tanstack/vue-query'
import '@vueuse/motion'
import 'core-js'

import 'vue-router'
import 'depcheck'
import 'prettier'
import 'eslint'
import 'sass'
import 'sass-embedded'
import 'ts-prune'
import 'vite-plugin-pwa'

import 'vue-eslint-parser'
import 'vue-tsc'
import '@vitest/coverage-v8'
import '@trpc/server'
import 'vitest-mock-extended'
import '@testing-library/jest-dom'
import '@vue/tsconfig'

import '@tailwindcss/postcss'
import 'postcss'
import '@trpc/server'
