import type { KnipConfig } from 'knip'
const config: KnipConfig = {
  project: ['./tsconfig.app.json', './tsconfig.node.json'],
  entry: ['src/main.ts'],

  ignoreDependencies: [
    '@tanstack/vue-query',
    '@vueuse/motion',
    'core-js',
    // 'vue-final-modal',
    'vue-router',
    'depcheck',
    'prettier',
    'eslint',
    'sass',
    'sass-embedded',
    'ts-prune',
    'vite-plugin-pwa',
    // '@vitest/coverage-istanbul',
    // 'lucide-vue-next',
    'vue-eslint-parser',
    'vue-tsc',
    '@vitest/coverage-v8',
    '@trpc/server',
    'vitest-mock-extended',
    '@testing-library/jest-dom',
    // '@vee-validate/zod',
    '@vue/tsconfig',
    // 'vee-validate',
    // 'zod',
    '@tailwindcss/postcss',
    'postcss',
  ],
  ignoreBinaries: [
    'vite',
    'vue-tsc',
    'eslint',
    'prettier',
    'stylelint',
    'vitest',
    'knip',
    'depcheck',
    'ts-prune',
    'wireit',
  ],
}

export default config
