services:
  server:
    container_name: fastify-server
    build:
      context: ../../server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - API_KEY=${API_KEY}
      - FRONTEND_ORIGIN=${FRONTEND_ORIGIN}
    volumes:
      - ../../server:/app
      - /app/node_modules
    command: yarn dev  # ✅ override CMD
    restart: always
    networks:
      - app_network
    profiles:
      - back
