services:
  server:
    container_name: fastify-server
    build:
      context: ../..
      dockerfile: server/Dockerfile
    working_dir: /app/server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - API_KEY=${API_KEY}
      - FRONTEND_ORIGIN=${FRONTEND_ORIGIN}
      - CNN_PREDICT_URL=${CNN_PREDICT_URL}
    volumes:
      - ../../server:/app/server
      - ../../package.json:/app/package.json
      - ../../yarn.lock:/app/yarn.lock
      - ../../.yarn:/app/.yarn
      - ../../.yarnrc.yml:/app/.yarnrc.yml
      - /app/node_modules

    command: yarn dev # ✅ override CMD
    restart: always
    networks:
      - app_network
    profiles:
      - back
