/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const EffectScope: typeof import('vue')['EffectScope']
  const computed: typeof import('vue')['computed']
  const createApp: typeof import('vue')['createApp']
  const customRef: typeof import('vue')['customRef']
  const defineAsyncComponent: typeof import('vue')['defineAsyncComponent']
  const defineComponent: typeof import('vue')['defineComponent']
  const effectScope: typeof import('vue')['effectScope']
  const getCurrentInstance: typeof import('vue')['getCurrentInstance']
  const getCurrentScope: typeof import('vue')['getCurrentScope']
  const getCurrentWatcher: typeof import('vue')['getCurrentWatcher']
  const h: typeof import('vue')['h']
  const inject: typeof import('vue')['inject']
  const injectHead: typeof import('@unhead/vue')['injectHead']
  const isProxy: typeof import('vue')['isProxy']
  const isReactive: typeof import('vue')['isReactive']
  const isReadonly: typeof import('vue')['isReadonly']
  const isRef: typeof import('vue')['isRef']
  const isShallow: typeof import('vue')['isShallow']
  const markRaw: typeof import('vue')['markRaw']
  const nextTick: typeof import('vue')['nextTick']
  const onActivated: typeof import('vue')['onActivated']
  const onBeforeMount: typeof import('vue')['onBeforeMount']
  const onBeforeRouteLeave: (typeof import('vue-router'))['onBeforeRouteLeave']
  const onBeforeRouteUpdate: (typeof import('vue-router'))['onBeforeRouteUpdate']
  const onBeforeUnmount: typeof import('vue')['onBeforeUnmount']
  const onBeforeUpdate: typeof import('vue')['onBeforeUpdate']
  const onDeactivated: typeof import('vue')['onDeactivated']
  const onErrorCaptured: typeof import('vue')['onErrorCaptured']
  const onMounted: typeof import('vue')['onMounted']
  const onRenderTracked: typeof import('vue')['onRenderTracked']
  const onRenderTriggered: typeof import('vue')['onRenderTriggered']
  const onScopeDispose: typeof import('vue')['onScopeDispose']
  const onServerPrefetch: typeof import('vue')['onServerPrefetch']
  const onUnmounted: typeof import('vue')['onUnmounted']
  const onUpdated: typeof import('vue')['onUpdated']
  const onWatcherCleanup: typeof import('vue')['onWatcherCleanup']
  const provide: typeof import('vue')['provide']
  const queryClient: typeof import('@/plugins/tanstack')['queryClient']
  const reactive: typeof import('vue')['reactive']
  const readonly: typeof import('vue')['readonly']
  const ref: typeof import('vue')['ref']
  const resolveComponent: typeof import('vue')['resolveComponent']
  const shallowReactive: typeof import('vue')['shallowReactive']
  const shallowReadonly: typeof import('vue')['shallowReadonly']
  const shallowRef: typeof import('vue')['shallowRef']
  const stores: typeof import('./stores/index')['default']
  const toRaw: typeof import('vue')['toRaw']
  const toRef: typeof import('vue')['toRef']
  const toRefs: typeof import('vue')['toRefs']
  const toValue: typeof import('vue')['toValue']
  const triggerRef: typeof import('vue')['triggerRef']
  const unref: typeof import('vue')['unref']
  const useAppStore: typeof import('./stores/app')['useAppStore']
  const useAttrs: typeof import('vue')['useAttrs']
  const useAuthForm: typeof import('./composables/useAuthForm')['useAuthForm']
  const useAuthStore: typeof import('./stores/auth')['useAuthStore']
  const useCanvasAnimation: typeof import('./composables/useCanvasAnimation')['useCanvasAnimation']
  const useChatScroll: typeof import('./composables/useChatScroll')['useChatScroll']
  const useChatStore: typeof import('./stores/chatStore')['useChatStore']
  const useClock: typeof import('./composables/useClock')['useClock']
  const useCssModule: typeof import('vue')['useCssModule']
  const useCssVars: typeof import('vue')['useCssVars']
  const useFileUpload: typeof import('./composables/useFileUpload')['useFileUpload']
  const useGenerateKeyHandler: typeof import('./composables/useAuthHandler')['useGenerateKeyHandler']
  const useGitHubCallback: (typeof import('./composables/useGitHubCallback'))['useGitHubCallback']
  const useGitHubLogin: (typeof import('./composables/useGitHubLogin'))['useGitHubLogin']
  const useGithubCallbackHandler: typeof import('./composables/useAuthHandler')['useGithubCallbackHandler']
  const useGlobalFileDragState: typeof import('./composables/useGlobalFileDragState')['useGlobalFileDragState']
  const useGoogleCallbackHandler: typeof import('./composables/useAuthHandler')['useGoogleCallbackHandler']
  const useHead: typeof import('@unhead/vue')['useHead']
  const useHeadSafe: typeof import('@unhead/vue')['useHeadSafe']
  const useId: typeof import('vue')['useId']
  const useImagePredictor: typeof import('./composables/useImagePredictor')['useImagePredictor']
  const useLink: (typeof import('vue-router'))['useLink']
  const useModel: typeof import('vue')['useModel']
  const useOximeterStore: typeof import('./stores/oximeterStore')['useOximeterStore']
  const usePixiBackground: typeof import('./composables/usePixiBackground')['usePixiBackground']
  const usePixiBgConfig: typeof import('./composables/usePixiBgConfig')['usePixiBgConfig']
  const usePixiBgStore: typeof import('./stores/pixiBgStore')['usePixiBgStore']
  const usePixiHeartbeat: typeof import('./composables/usePixiHeartbeat')['usePixiHeartbeat']
  const usePixiPulse: typeof import('./composables/usePixiPulse')['usePixiPulse']
  const usePixiTextures: typeof import('./composables/usePixiTextures')['usePixiTextures']
  const useRoute: typeof import('vue-router/auto')['useRoute']
  const useRouter: typeof import('vue-router/auto')['useRouter']
  const useSeoMeta: typeof import('@unhead/vue')['useSeoMeta']
  const useServerHead: typeof import('@unhead/vue')['useServerHead']
  const useServerHeadSafe: typeof import('@unhead/vue')['useServerHeadSafe']
  const useServerPulse: typeof import('./composables/useServerPulse')['useServerPulse']
  const useServerPulseStore: (typeof import('./stores/oximeterStore'))['useServerPulseStore']
  const useServerSeoMeta: typeof import('@unhead/vue')['useServerSeoMeta']
  const useSession: typeof import('./composables/useSession')['useSession']
  const useSlots: typeof import('vue')['useSlots']
  const useStorageStore: typeof import('./stores/storageStore')['useStorageStore']
  const useTRPC: typeof import('./composables/useTRPC')['useTRPC']
  const useTemplateRef: typeof import('vue')['useTemplateRef']
  const useTheme: typeof import('./composables/useTheme')['useTheme']
  const useThemeStore: typeof import('./stores/themeStore')['useThemeStore']
  const watch: typeof import('vue')['watch']
  const watchEffect: typeof import('vue')['watchEffect']
  const watchPostEffect: typeof import('vue')['watchPostEffect']
  const watchSyncEffect: typeof import('vue')['watchSyncEffect']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { FileUploadResult } from './composables/useFileUpload'
  import('./composables/useFileUpload')
  // @ts-ignore
  export type { PredictionResult } from './composables/useImagePredictor'
  import('./composables/useImagePredictor')
  // @ts-ignore
  export type { MedShape } from './composables/usePixiTextures'
  import('./composables/usePixiTextures')
  // @ts-ignore
  export type { ThemeMode } from './stores/themeStore'
  import('./stores/themeStore')
}
