/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatMessage: typeof import('./components/ChatMessage.vue')['default']
    ChatWindow: typeof import('./components/ChatWindow.vue')['default']
    ClockDisplay: typeof import('./components/ClockDisplay.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HoverImage: typeof import('./components/HoverImage.vue')['default']
    ImageModal: typeof import('./components/ImageModal.vue')['default']
    ImagePreview: typeof import('./components/ImagePreview.vue')['default']
    MessageInput: typeof import('./components/MessageInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollToBottomButton: typeof import('./components/ScrollToBottomButton.vue')['default']
  }
}
