/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApiKeyContent: typeof import('./components/ApiKeyContent.vue')['default']
    ApiKeyModal: typeof import('./components/ApiKeyModal.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AuthForm: typeof import('./components/AuthForm.vue')['default']
    CanvasBackground: typeof import('./components/CanvasBackground.vue')['default']
    ChatMessage: typeof import('./components/ChatMessage.vue')['default']
    ChatWindow: typeof import('./components/ChatWindow.vue')['default']
    ClockDisplay: typeof import('./components/ClockDisplay.vue')['default']
    FileInput: typeof import('./components/FileInput.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HoverImage: typeof import('./components/HoverImage.vue')['default']
    ImageModal: typeof import('./components/ImageModal.vue')['default']
    ImagePreview: typeof import('./components/ImagePreview.vue')['default']
    LoginButton: typeof import('./components/LoginButton.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    LogoutButton: typeof import('./components/LogoutButton.vue')['default']
    MessageInput: typeof import('./components/MessageInput.vue')['default']
    PixiBackground: typeof import('./components/PixiBackground.vue')['default']
    ProfileModal: typeof import('./components/ProfileModal.vue')['default']
    ResponsiveModal: typeof import('./components/ResponsiveModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollToBottomButton: typeof import('./components/ScrollToBottomButton.vue')['default']
    SettingsModal: typeof import('./components/SettingsModal.vue')['default']
  }
}
