include:
  - path: "docker/db/compose.yml"
  # - path: "docker/tools/compose.yml"
  - path: "docker/server/compose.yml"
  - path: "docker/client/compose.yml"
volumes:
  db_data:
  pgadmin_data:

networks:
  app_network:
