[build]
  base = "client"
  command = "yarn build"
  publish = "client/dist"


[context.production.environment]
  NODE_VERSION = "18"

[context.deploy-preview.environment]
  NODE_VERSION = "18"

[context.branch-deploy.environment]
  NODE_VERSION = "18"
