services:
  client:
    container_name: client
    build:
      context: ../../client
      dockerfile: Dockerfile.dev
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ../../client:/app
      - /app/node_modules
    command: yarn dev
    environment:
      - HOST=0.0.0.0
    profiles:
      - front
    networks:
      - app_network
