services:
  client:
    container_name: client
    build:
      context: ../..
      dockerfile: client/Dockerfile
    working_dir: /app/client
    ports:
      - "4000:4000"
    volumes:
      - ../..:/app
      - /app/node_modules
    command: yarn dev
    environment:
      - HOST=0.0.0.0
    profiles:
      - front
    networks:
      - app_network
