services:
  client:
    container_name: client
    build:
      context: ../..
      dockerfile: client/Dockerfile
    working_dir: /app/client
    ports:
      - "4000:4000"
    volumes:
      - ../../client:/app/client # Only client files
      - ../../package.json:/app/package.json
      - ../../yarn.lock:/app/yarn.lock
      - ../../.yarn:/app/.yarn
      - ../../.yarnrc.yml:/app/.yarnrc.yml
      - /app/node_modules

    command: yarn dev
    environment:
      - HOST=0.0.0.0
      - VITE_API_KEY=${VITE_API_KEY}
    profiles:
      - front
    networks:
      - app_network
