name: 🛠️ Setup Yarn 4 Project
description: Common setup for Yarn 4-based monorepo workspaces

inputs:
  node-version:
    description: Node.js version
    required: false
    default: "20"
  working-directory:
    description: Directory where commands should run
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: 🧱 Checkout code
      uses: actions/checkout@v4

    - name: 🧶 Enable Corepack and Yarn v4
      shell: bash
      run: |
        corepack enable
        corepack prepare yarn@4.7.0 --activate

    - name: 🔧 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: yarn

    - name: 📦 Install dependencies
      shell: bash
      run: yarn install --immutable
      working-directory: ${{ inputs.working-directory }}
